### ISSUE TITLE
[DOCUMENTATION] Create changelog

### ISSUE THREAD

**Issue by hipio** [DealerDirect/short-uuid-bundle#7]
A changelog has to be included in this repository to make changes more easily visible.

**Comment by Potherca** [comment]
For reference:
- http://keepachangelog.com/
- the [diff between v0.0.0...v0.1.0](https://github.com/DealerDirect/short-uuid-bundle/compare/0402f04...v0.1.0)
- the [diff between v0.1.0...v0.2.0](https://github.com/DealerDirect/short-uuid-bundle/compare/v0.1.0...v0.2.0)
- the [diff between v0.2.0...v0.2.1](https://github.com/DealerDirect/short-uuid-bundle/compare/v0.2.0...v0.2.0.1)

**Comment by hipio** [comment]
@Potherca does this new PR (#9) resolve your issue?

**Comment by Potherca** [comment]
Yup.
